"""Curated domains eligible for trusted-domain verification.

This selected list of well-known official domains is not a universal whitelist.
Unknown domains must continue through Random Forest machine-learning analysis.
"""

TRUSTED_DOMAINS = frozenset(
    {
        # Search engines
        "google.com",
        "bing.com",
        "yahoo.com",
        "duckduckgo.com",
        "baidu.com",
        "yandex.com",
        "ecosia.org",
        "brave.com",
        # Google services
        "gmail.com",
        "googleapis.com",
        "googleusercontent.com",
        "googlevideo.com",
        "youtube.com",
        "youtu.be",
        "android.com",
        "chromium.org",
        "developers.google.com",
        "cloud.google.com",
        "firebase.google.com",
        "blog.google",
        "workspace.google.com",
        # Microsoft
        "microsoft.com",
        "live.com",
        "outlook.com",
        "office.com",
        "microsoftonline.com",
        "azure.com",
        "github.com",
        "linkedin.com",
        "xbox.com",
        "visualstudio.com",
        "windows.com",
        # Apple
        "apple.com",
        "icloud.com",
        "developer.apple.com",
        "itunes.com",
        # Amazon
        "amazon.com",
        "amazon.in",
        "amazon.co.uk",
        "amazon.de",
        "amazonaws.com",
        "aws.amazon.com",
        "primevideo.com",
        "imdb.com",
        "twitch.tv",
        "amazonpay.in",
        # Meta and social platforms
        "meta.com",
        "facebook.com",
        "instagram.com",
        "messenger.com",
        "whatsapp.com",
        "threads.net",
        "reddit.com",
        "discord.com",
        "telegram.org",
        "t.me",
        "x.com",
        "twitter.com",
        "tiktok.com",
        "snapchat.com",
        "pinterest.com",
        "tumblr.com",
        # Developer and programming
        "gitlab.com",
        "bitbucket.org",
        "stackoverflow.com",
        "stackexchange.com",
        "leetcode.com",
        "hackerrank.com",
        "codeforces.com",
        "codechef.com",
        "kaggle.com",
        "replit.com",
        "codepen.io",
        "jsfiddle.net",
        "npmjs.com",
        "pypi.org",
        "python.org",
        "java.com",
        "oracle.com",
        "cplusplus.com",
        "rust-lang.org",
        "golang.org",
        "php.net",
        "ruby-lang.org",
        "dotnet.microsoft.com",
        "developer.mozilla.org",
        "w3.org",
        "web.dev",
        "mozilla.org",
        # AI and machine learning
        "openai.com",
        "chatgpt.com",
        "platform.openai.com",
        "anthropic.com",
        "claude.ai",
        "huggingface.co",
        "deepmind.google",
        "perplexity.ai",
        "x.ai",
        "gemini.google.com",
        "ai.google",
        "cohere.com",
        "replicate.com",
        # Cloud and DevOps
        "cloudflare.com",
        "digitalocean.com",
        "heroku.com",
        "vercel.com",
        "netlify.com",
        "render.com",
        "railway.app",
        "docker.com",
        "docker.io",
        "kubernetes.io",
        "terraform.io",
        "hashicorp.com",
        "nginx.com",
        "apache.org",
        # Education
        "coursera.org",
        "edx.org",
        "udemy.com",
        "khanacademy.org",
        "wikipedia.org",
        "wikimedia.org",
        "mit.edu",
        "stanford.edu",
        "harvard.edu",
        "berkeley.edu",
        "cmu.edu",
        "ox.ac.uk",
        "cam.ac.uk",
        "iitb.ac.in",
        "iitd.ac.in",
        "iisc.ac.in",
        "nta.ac.in",
        "cbse.gov.in",
        "ugc.gov.in",
        "aicte-india.org",
        "swayam.gov.in",
        "nptel.ac.in",
        "diksha.gov.in",
        # Design and productivity
        "canva.com",
        "notion.so",
        "figma.com",
        "slack.com",
        "zoom.us",
        "trello.com",
        "atlassian.com",
        "asana.com",
        "monday.com",
        "dropbox.com",
        "box.com",
        "evernote.com",
        "grammarly.com",
        # Entertainment
        "netflix.com",
        "spotify.com",
        "disneyplus.com",
        "hulu.com",
        "rottentomatoes.com",
        # Shopping and consumer brands
        "ebay.com",
        "walmart.com",
        "target.com",
        "bestbuy.com",
        "etsy.com",
        "shopify.com",
        "nike.com",
        "adidas.com",
        "puma.com",
        "samsung.com",
        # Payments and fintech
        "paypal.com",
        "stripe.com",
        "visa.com",
        "mastercard.com",
        "americanexpress.com",
        "wise.com",
        "venmo.com",
        "cash.app",
        "razorpay.com",
        "paytm.com",
        "phonepe.com",
        "googlepay.com",
        "upi.org.in",
        "npci.org.in",
        # Explicit India government and public services.
        # Listing gov.in/nic.in is intentional and does not trust arbitrary
        # domains that merely contain these strings.
        "gov.in",
        "nic.in",
        "india.gov.in",
        "mygov.in",
        "digitalindia.gov.in",
        "uidai.gov.in",
        "incometax.gov.in",
        "gst.gov.in",
        "mca.gov.in",
        "epfindia.gov.in",
        "passportindia.gov.in",
        "parivahan.gov.in",
        "irctc.co.in",
        "indianrail.gov.in",
        # India banking
        "sbi.co.in",
        "onlinesbi.sbi",
        "hdfcbank.com",
        "icicibank.com",
        "axisbank.com",
        "kotak.com",
        "bankofbaroda.in",
        "pnbindia.in",
        "canarabank.com",
        "indianbank.in",
        "unionbankofindia.co.in",
        "idfcfirstbank.com",
        "yesbank.in",
        "indusind.com",
        "federalbank.co.in",
        # India travel, transport and education
        "airindia.com",
        "goindigo.in",
        "akasaair.com",
        "ksrtc.in",
        "redbus.in",
        "makemytrip.com",
        # News and media
        "bbc.com",
        "cnn.com",
        "reuters.com",
        "theguardian.com",
        "nytimes.com",
        "washingtonpost.com",
        "ndtv.com",
        "hindustantimes.com",
        "thehindu.com",
        "timesofindia.indiatimes.com",
        "indianexpress.com",
        # Security and technology vendors
        "kaspersky.com",
        "mcafee.com",
        "norton.com",
        "avast.com",
        "bitdefender.com",
        "sophos.com",
        "crowdstrike.com",
        "cisco.com",
        "intel.com",
        "amd.com",
        "nvidia.com",
        "qualcomm.com",
    }
)
